version: "3.8"

services:
  
  app:
    image: jpbusta/fininstitute:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    depends_on:
      - db
    restart: always
    
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=finInstitution
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_init.sql
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres-data:
    external: true

