name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run containers
        run: |
          docker-compose up --build --no-start
          docker-compose start
          docker-compose ps

      - name: Run tests
        run: |
          # Run your tests here against the running containers

      - name: Tear down containers
        run: docker-compose down
