on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run containers
        run: |
          docker volume create --name=postgres-data
          docker-compose up --build --no-start app db tests

      - name: Run tests
        run: |
          docker-compose start app db
          docker-compose exec tests npx mocha

      - name: Show test logs
        run: |
          docker-compose logs tests

      - name: Tear down containers
        run: docker-compose down
