on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run containers
        run: |
          docker volume create --name=postgres-data
          docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build --no-start
          docker-compose -f docker-compose.yml -f docker-compose.test.yml start
          docker-compose -f docker-compose.yml -f docker-compose.test.yml ps

      - name: Wait for containers to start
        run: sleep 10s

      - name: Expose container ports
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml port app 3000
          docker-compose -f docker-compose.yml -f docker-compose.test.yml port db 5432

      - name: Run tests
        run: |
          docker exec CI npx mocha

      - name: Tear down containers
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml down
