name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run containers
        run: |
              docker volume create --name=postgres-data
              docker-compose up --build --no-start
              docker-compose start
              docker-compose ps

      - name: Run tests
        run: |
          npx mocha

      - name: Tear down containers
        run: docker-compose down
