on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and run containers
        run: |
          docker volume create --name=postgres-data
          docker-compose up --build --no-start
          docker-compose start
          docker-compose ps

      - name: Expose container ports
        run: |
          docker-compose port app 3000
          docker-compose port db 5432

      - name: Run tests
        run: |
          docker-compose restart tests
          docker logs -f finantialinstitution-tests-1

      - name: Tear down containers
        run: docker-compose down
